### ISSUE TITLE
希望支持从本地路径读取包名，用户可以自己维护名单

### ISSUE THREAD

**Issue by wsxwd** [PharosVip/Pharos-Android-Test#11]
这是简单的配置文件示例，proxy表示全局代理，package name字段无效。whitelist表示仅package name字段的包通过代理，其余包均不通过代理。blacklist表示仅package name字段的包不通过代理，其余包均通过代理。

[mode]
mode  = proxy or whitelist or blacklist

[package name]
com.google.android.apps.googlevoice
com.google.android.apps.magazines

**Comment by PharosVip** [comment]
good
