### ISSUE TITLE
请求增加忽略：see微博客户端、share微博客户端

### ISSUE THREAD

**Issue by ghost** [PharosVip/Pharos-Android-Test#21]
安卓应用：see微博客户端、share微博客户端，目前没有被忽略代理，开启Pharos后这两个第三方微博客户端加载图片和视频严重受影响。

**Comment by PharosVip** [comment]
udpate to the proxy list version

**Comment by ghost** [comment]
> udpate to the proxy list version

请问添加进Bypass了吗？新版本啥时候发？（还是说不需要更新新版本，是以动态URL的规则形式获取更新bypass的？）
