### ISSUE TITLE
请求支持 SIP002 URIs 订阅格式

### ISSUE THREAD

**Issue by nameless3721** [PharosVip/Pharos-Android-Test#4]
https://shadowsocks.org/en/spec/SIP002-URI-Scheme.html  好像是这个 还有ss支持域名解析 dns自定义

**Comment by PharosVip** [comment]
尚未支持 simple obfs

**Comment by nameless3721** [comment]
> 尚未支持 simple obfs

支持订阅格式解析就好了  不是全部ss都有obfs的

**Comment by PharosVip** [comment]
> > 尚未支持 simple obfs
> 
> 支持订阅格式解析就好了 不是全部ss都有obfs的

新版本已经支持

**Comment by PharosVip** [comment]
see https://github.com/PharosVip/Pharos-Android-Test/releases/tag/1.1
