### ISSUE TITLE
推荐个白嫖机场

### ISSUE THREAD

**Issue by BruceLee569** [PharosVip/Pharos-Android-Test#42]
支持 V2Ray 和 Trojan，号称永不被封，实测免费节点晚上上网高峰时段，看油管 2K 无压力。

注册免费送三天，可连续白嫖，最主要的是不限流量不限速！

速度上限 100Mb/s，秒开 YouTube 、Ins，还能看奈飞 /Netflix 、Hulu 、HBO 、动画疯、TVB 、Apple TV...

无惧封锁，Trojan 、V2Ray 协议超强抗封锁，也支持 SSR 的哦。

机场名字叫西部世界，开很多年了，注册链接: https://xbsj9895.xyz/i/iv200411/KBjnPHE

**Comment by petcat** [comment]
这垃圾机场就别介绍了，也就白嫖三天临时用用，

我来介绍个真正可以白嫖的机场，免费用户每月30G流量，签到还有流量赠送，免费节点有8个，俄罗斯和新加坡的，要求只是要保持活跃，长时间不用会清理，账户有余额不会清理，你可以充个最低金额就不会删号。你不充值也行，就是要保持登陆、签到。注册地址： https://httpd.club/j

注意：免费节点只有SSR，付费才有v2ray，不过这家也不贵，35块/月就有IPLC节点用
